import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Save, ArrowLeft, Upload, FileText } from 'lucide-react';
import InventarisApi from '../../../api/InventarisApi';
import NamaAlatApi from '../../../api/NamaAlatApi';
import RuanganApi from '../../../api/RuanganApi';
import DivisiApi from '../../../api/DivisiApi';
import { usePageTitle } from '../../../hooks';
import Button from '../../../components/Button';
import Input from '../../../components/Input';
import Select from '../../../components/Select';
import SearchableSelect from '../../../components/SearchableSelect';
import { Toast } from '../../../components/Alert/Alert';

export default function InventarisForm() {
  const navigate = useNavigate();
  const { id } = useParams();
  const isEdit = !!id;
  usePageTitle(isEdit ? 'Edit Inventaris' : 'Tambah Inventaris');

  const [loading, setLoading] = useState(false);
  const [dataLoading, setDataLoading] = useState(true);
  const [toast, setToast] = useState(null);

  // Dropdown Data
  const [namaAlatOptions, setNamaAlatOptions] = useState([]);
  const [ruanganOptions, setRuanganOptions] = useState([]);
  const [divisiOptions, setDivisiOptions] = useState([]);
  // Store full data for lookup
  const [namaAlatData, setNamaAlatData] = useState([]);

  const [formData, setFormData] = useState({
    nama_alat_id: '',
    ruang_sekarang: '', // Will show placeholder instead of default value
    kategori_alat_id: '',
    ruangan_id: '',
    divisi_id: '',
    merk: '',
    model: '',
    seri: '',
    daya: '',
    // no_inventaris is auto-generated by backend
    harga: '',
    tahun_pengadaan: '',
    gedung: '',
    kondisi_alat: '', // Will show placeholder instead of default 'Baik'
    kategori_alkes: '',
    alat_kesehatan: false,
    interval_maintenance: '',
    awal_kalibrasi: '',
    kadaluwarsa: '',
    img_alat: null,
    file_sertifikat: null,
    file_sop: null
  });

  const [previews, setPreviews] = useState({
    img_alat: null
  });

  const [existingFiles, setExistingFiles] = useState({
    file_sertifikat: null,
    file_sop: null
  });

  // Helper function to generate year options (2001 to current year + 5)
  const generateYearOptions = () => {
    const currentYear = new Date().getFullYear();
    const startYear = 2001;
    const endYear = currentYear + 5;
    const years = [];

    for (let year = endYear; year >= startYear; year--) {
      years.push({ value: year.toString(), label: year.toString() });
    }

    return years;
  };

  // Set default tahun to current year on mount (for new form only)
  useEffect(() => {
    if (!isEdit && !formData.tahun_pengadaan) {
      setFormData(prev => ({ ...prev, tahun_pengadaan: new Date().getFullYear().toString() }));
    }
  }, [isEdit]);

  useEffect(() => {
    const fetchMasterData = async () => {
      try {
        const [alatRes, roomRes, divRes] = await Promise.all([
          NamaAlatApi.getAll(),
          RuanganApi.getAll(),
          DivisiApi.getAllRaw()
        ]);

        const rawAlat = Array.isArray(alatRes) ? alatRes : [];
        setNamaAlatData(rawAlat);
        setNamaAlatOptions(rawAlat.map(item => ({ value: item.id, label: item.nama_nama_alat })));

        // Fix: use id_ruangan instead of id for ruangan options
        const ruanganOpts = Array.isArray(roomRes) ? roomRes.map(item => ({
          value: item.id_ruangan,
          label: item.nama_ruangan
        })) : [];
        setRuanganOptions(ruanganOpts);

        // Fix: use id_divisi instead of id for divisi options
        const divisiOpts = Array.isArray(divRes) ? divRes.map(item => ({
          value: item.id_divisi,
          label: item.nama_divisi
        })) : [];
        setDivisiOptions(divisiOpts);

      } catch (error) {
        console.error("Failed to load master data", error);
        setToast({ type: 'error', message: 'Gagal memuat data master' });
      } finally {
        if (!isEdit) setDataLoading(false);
      }
    };

    fetchMasterData();
  }, []);

  // Set dataLoading to false for new forms
  useEffect(() => {
    if (!isEdit) {
      setDataLoading(false);
    }
  }, [isEdit]);

  useEffect(() => {
    if (isEdit) {
      const fetchInventaris = async () => {
        try {
          const data = await InventarisApi.getById(id);
          setFormData({
            nama_alat_id: data.nama_alat?.id || '',
            ruang_sekarang: data.ruangan_sekarang?.id_ruangan || data.ruangan?.id_ruangan || '',
            kategori_alat_id: data.nama_alat?.kategori_alat_id || '',
            ruangan_id: data.ruangan?.id_ruangan || '',
            divisi_id: data.divisi?.id_divisi || data.nama_alat?.divisi?.id_divisi || '',
            merk: data.merk || '',
            model: data.model || '',
            seri: data.seri || '',
            daya: data.daya || '',
            no_inventaris: data.no_inventaris || '',
            harga: data.harga || '',
            tahun_pengadaan: data.tahun_pengadaan || '',
            gedung: data.gedung || '',
            kondisi_alat: data.kondisi_alat || '',
            kategori_alkes: data.kategori_alkes || '',
            alat_kesehatan: !!data.alat_kesehatan,
            interval_maintenance: data.interval_maintenance || '',
            awal_kalibrasi: data.awal_kalibrasi || '',
            kadaluwarsa: data.kadaluwarsa || '',
            img_alat: null,
            file_sertifikat: null,
            file_sop: null
          });

          // Set Previews & Existing Files
          if (data.img_alat_url) {
            setPreviews(prev => ({ ...prev, img_alat: data.img_alat_url }));
          }

          setExistingFiles({
            file_sertifikat: data.file_sertifikat_url,
            file_sop: data.file_sop_url
          });




        } catch (error) {
          console.error("Failed to fetch inventaris", error);
          setToast({ type: 'error', message: 'Gagal memuat data inventaris' });
        } finally {
          setDataLoading(false);
        }
      };
      fetchInventaris();
    }
  }, [id, isEdit]);

  const handleChange = (e) => {
    const { name, value, type, checked, files } = e.target;

    if (type === 'file') {
      const file = files[0];
      setFormData(prev => ({ ...prev, [name]: file }));

      if (name === 'img_alat' && file) {
        const objectUrl = URL.createObjectURL(file);
        setPreviews(prev => ({ ...prev, [name]: objectUrl }));
      }
    } else if (type === 'checkbox') {
      setFormData(prev => ({ ...prev, [name]: checked }));
    } else {
      setFormData(prev => ({ ...prev, [name]: value }));

      // Filter Nama Alat when Divisi is changed
      if (name === 'divisi_id') {
        // Filter nama alat berdasarkan divisi
        const filteredAlat = value
          ? namaAlatData.filter(item => String(item.divisi_id) === String(value))
          : namaAlatData;

        setNamaAlatOptions(filteredAlat.map(item => ({ value: item.id, label: item.nama_nama_alat })));

        // Reset nama_alat_id dan kategori_alat_id jika divisi berubah
        setFormData(prev => ({ ...prev, [name]: value, nama_alat_id: '', kategori_alat_id: '' }));
      }
      // Auto-set Kategori Alat if Nama Alat is changed
      else if (name === 'nama_alat_id') {
        const selectedAlat = namaAlatData.find(item => String(item.id) === String(value));
        if (selectedAlat && selectedAlat.kategori_alat_id) {
          setFormData(prev => ({ ...prev, kategori_alat_id: selectedAlat.kategori_alat_id, [name]: value }));
        }
      }
    }
  };

  // Auto-preview no_inventaris when required fields are filled
  useEffect(() => {
    const previewNoInventaris = async () => {
      if (formData.nama_alat_id && formData.ruangan_id && formData.tahun_pengadaan && !isEdit) {
        try {
          const payload = {
            nama_alat_id: formData.nama_alat_id,
            ruangan_id: formData.ruangan_id,
            tahun_pengadaan: formData.tahun_pengadaan
          };

          const response = await InventarisApi.previewNoInventaris(payload);

          if (response.status === 'success' && response.data.no_inventaris) {
            setFormData(prev => ({ ...prev, no_inventaris: response.data.no_inventaris }));
          }
        } catch (error) {
          console.error('Failed to preview no_inventaris:', error);
          console.error('Error response:', error.response?.data);
        }
      }
    };

    previewNoInventaris();
  }, [formData.nama_alat_id, formData.ruangan_id, formData.tahun_pengadaan, isEdit]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    try {
      // Create FormData
      const payload = new FormData();
      Object.keys(formData).forEach(key => {
        const value = formData[key];
        if (value !== null && value !== undefined && value !== '') {
          // Boolean handling for FormData
          if (typeof value === 'boolean') {
            payload.append(key, value ? '1' : '0');
          } else {
            payload.append(key, value);
          }
        }
      });

      if (isEdit) {
        await InventarisApi.update(id, payload);
        setToast({ type: 'success', message: 'Data berhasil diperbarui' });
      } else {
        await InventarisApi.create(payload);
        setToast({ type: 'success', message: 'Data berhasil ditambahkan' });
      }

      setTimeout(() => navigate('/inventaris/data'), 1500);

    } catch (error) {
      console.error('Submit error:', error);
      console.error('Error response:', error.response?.data);
      const msg = error.response?.data?.message || 'Gagal menyimpan data';
      const errors = error.response?.data?.errors;
      if (errors) {
        console.error('Validation errors:', errors);
        const errorMessages = Object.values(errors).flat().join(', ');
        setToast({ type: 'error', message: `${msg}: ${errorMessages}` });
      } else {
        setToast({ type: 'error', message: msg });
      }
    } finally {
      setLoading(false);
    }
  };

  if (dataLoading) {
    return <div className="p-8 text-center bg-white rounded-2xl">Memuat data...</div>;
  }

  return (
    <div className="animate-fade-in space-y-6">
      {toast && (
        <div className="fixed top-6 right-6 z-50">
          <Toast type={toast.type} message={toast.message} onClose={() => setToast(null)} />
        </div>
      )}

      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" onClick={() => navigate('/inventaris/data')} className="p-2">
          <ArrowLeft size={24} />
        </Button>
        <div>
          <h1 className="text-2xl font-bold text-text-dark">
            {isEdit ? 'Edit Data Alat' : 'Tambah Alat Baru'}
          </h1>
          <p className="text-gray-500 text-sm">Lengkapi data inventaris alat di bawah ini</p>
        </div>
      </div>

      <div className="bg-white rounded-[24px] p-8 shadow-[0px_10px_40px_rgba(29,22,23,0.03)]">
        <form onSubmit={handleSubmit} className="space-y-8">

          {/* Section 1: Informasi Utama */}
          <div>
            <h3 className="text-lg font-bold text-text-dark mb-4 border-b pb-2">Informasi Utama</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <SearchableSelect
                label="Divisi"
                name="divisi_id"
                options={divisiOptions}
                value={formData.divisi_id}
                onChange={handleChange}
                placeholder="Pilih Divisi"
                searchPlaceholder="Cari divisi..."
                required
              />
              <SearchableSelect
                label="Nama Alat (Master)"
                name="nama_alat_id"
                options={namaAlatOptions}
                value={formData.nama_alat_id}
                onChange={handleChange}
                placeholder="Pilih Nama Alat"
                searchPlaceholder="Cari nama alat..."
                required
                disabled={isEdit || !formData.divisi_id}
              />
              <SearchableSelect
                label="Ruangan"
                name="ruangan_id"
                options={ruanganOptions}
                value={formData.ruangan_id}
                onChange={handleChange}
                placeholder="Pilih Ruangan"
                searchPlaceholder="Cari ruangan..."
                required
              />
              <Input
                label="No Inventaris"
                name="no_inventaris"
                value={formData.no_inventaris}
                onChange={handleChange}
                placeholder="Auto-generated"
                readOnly
                disabled
                className="bg-gray-50"
              />
              <SearchableSelect
                label="Ruang Sekarang"
                name="ruang_sekarang"
                options={ruanganOptions}
                value={formData.ruang_sekarang}
                onChange={handleChange}
                placeholder="Pilih Ruangan"
                searchPlaceholder="Cari ruangan..."
                required
              />
              <Input
                label="Gedung"
                name="gedung"
                value={formData.gedung}
                onChange={handleChange}
                placeholder="Contoh: Gedung A"
                required
              />
            </div>
          </div>

          {/* Section 2: Detail Spesifikasi */}
          <div>
            <h3 className="text-lg font-bold text-text-dark mb-4 border-b pb-2">Spesifikasi Alat</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <Input
                label="Merk"
                name="merk"
                value={formData.merk}
                onChange={handleChange}
                required
              />
              <Input
                label="Tipe / Model"
                name="model"
                value={formData.model}
                onChange={handleChange}
                required
              />
              <Input
                label="Nomor Seri (SN)"
                name="seri"
                value={formData.seri}
                onChange={handleChange}
                required
              />
              <Input
                label="Daya (Watt/Volt)"
                name="daya"
                value={formData.daya}
                onChange={handleChange}
              />
              <SearchableSelect
                label="Tahun Pengadaan"
                name="tahun_pengadaan"
                value={formData.tahun_pengadaan}
                onChange={handleChange}
                options={generateYearOptions()}
                placeholder="Pilih Tahun"
                searchPlaceholder="Cari tahun..."
                required
              />
              <Input
                label="Harga Perolehan (Rp)"
                name="harga"
                currency
                value={formData.harga}
                onChange={handleChange}
                required
              />
            </div>
          </div>

          {/* Section 3: Status & Kondisi */}
          <div>
            <h3 className="text-lg font-bold text-text-dark mb-4 border-b pb-2">Status & Kondisi</h3>

            {/* Logic Toggle Alat Kesehatan */}
            <div className="mb-6 flex items-center gap-2 bg-purple-50 p-4 rounded-xl border border-purple-100">
              <input
                type="checkbox"
                id="alat_kesehatan"
                name="alat_kesehatan"
                checked={formData.alat_kesehatan}
                onChange={handleChange}
                className="w-5 h-5 text-brand-primary rounded border-gray-300 focus:ring-brand-primary"
              />
              <label htmlFor="alat_kesehatan" className="font-bold text-text-dark cursor-pointer selection:bg-none">
                Apakah termasuk alat kesehatan?
              </label>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {/* Conditional Rendering Kategori Alkes */}
              {formData.alat_kesehatan && (
                <div className="animate-fade-in-down">
                  <SearchableSelect
                    label="Kategori Alat Kesehatan"
                    name="kategori_alkes"
                    value={formData.kategori_alkes}
                    onChange={handleChange}
                    options={[
                      { value: 'Sederhana', label: 'Sederhana' },
                      { value: 'Menengah', label: 'Menengah' },
                      { value: 'Canggih', label: 'Canggih' },
                    ]}
                    placeholder="Pilih Kategori Alat Kesehatan"
                    searchPlaceholder="Cari kategori..."
                    required
                  />
                </div>
              )}

              <SearchableSelect
                label="Kondisi Alat"
                name="kondisi_alat"
                value={formData.kondisi_alat}
                onChange={handleChange}
                options={[
                  { value: 'Baik', label: 'Baik' },
                  { value: 'Rusak Ringan', label: 'Rusak Ringan' },
                  { value: 'Rusak Berat', label: 'Rusak Berat' },
                  { value: 'Dalam Perbaikan', label: 'Dalam Perbaikan' },
                ]}
                placeholder="Pilih Kondisi Alat"
                searchPlaceholder="Cari kondisi..."
              />

              <Input
                label="Interval Maintenance (Tahun)"
                name="interval_maintenance"
                type="number"
                value={formData.interval_maintenance}
                onChange={handleChange}
                placeholder="Masukkan Interval Maintenance"
                required // Added asterisk logic visually by 'required' prop in reusable component if supported, or via label
              />

              <Input
                label="Awal Kalibrasi"
                name="awal_kalibrasi"
                type="date"
                value={formData.awal_kalibrasi}
                onChange={handleChange}
              />
              <Input
                label="Kadaluwarsa"
                name="kadaluwarsa"
                type="date"
                value={formData.kadaluwarsa}
                onChange={handleChange}
              />
            </div>
          </div>

          {/* Section 4: File Uploads */}
          <div>
            <h3 className="text-lg font-bold text-text-dark mb-4 border-b pb-2">Berkas & Foto</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="border-2 border-dashed border-gray-200 rounded-xl p-6 text-center hover:bg-gray-50 transition-colors">
                <input type="file" name="img_alat" id="img_alat" className="hidden" onChange={handleChange} accept="image/*" />
                <label htmlFor="img_alat" className="cursor-pointer block">
                  {previews.img_alat ? (
                    <img src={previews.img_alat} alt="Preview" className="h-32 mx-auto object-contain mb-2" />
                  ) : (
                    <Upload className="mx-auto h-10 w-10 text-gray-400 mb-2" />
                  )}
                  <span className="font-bold text-brand-primary">Upload Foto Alat</span>
                  <p className="text-xs text-gray-400 mt-1">.jpg, .png (Max 2MB)</p>
                  {formData.img_alat && typeof formData.img_alat === 'object' && (
                    <p className="text-sm text-green-600 mt-2 font-medium">{formData.img_alat.name}</p>
                  )}
                </label>
              </div>

              <div className="border-2 border-dashed border-gray-200 rounded-xl p-6 text-center hover:bg-gray-50 transition-colors">
                <input type="file" name="file_sertifikat" id="file_sertifikat" className="hidden" onChange={handleChange} accept=".pdf" />
                <label htmlFor="file_sertifikat" className="cursor-pointer block">
                  <FileText className="mx-auto h-10 w-10 text-gray-400 mb-2" />
                  <span className="font-bold text-brand-primary">Upload Sertifikat</span>
                  <p className="text-xs text-gray-400 mt-1">.pdf (Max 5MB)</p>

                  {/* Show new file name */}
                  {formData.file_sertifikat && (
                    <p className="text-sm text-green-600 mt-2 font-medium bg-green-50 py-1 px-2 rounded-lg inline-block">
                      {formData.file_sertifikat.name}
                    </p>
                  )}

                  {/* Show existing file if no new file selected */}
                  {!formData.file_sertifikat && existingFiles.file_sertifikat && (
                    <div className="mt-2 text-sm">
                      <p className="text-blue-600 font-medium mb-1">File saat ini tersimpan</p>
                      <a
                        href={existingFiles.file_sertifikat}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-gray-500 hover:text-brand-primary underline"
                        onClick={(e) => e.stopPropagation()}
                      >
                        Lihat Sertifikat
                      </a>
                    </div>
                  )}
                </label>
              </div>

              <div className="border-2 border-dashed border-gray-200 rounded-xl p-6 text-center hover:bg-gray-50 transition-colors">
                <input type="file" name="file_sop" id="file_sop" className="hidden" onChange={handleChange} accept=".pdf" />
                <label htmlFor="file_sop" className="cursor-pointer block">
                  <FileText className="mx-auto h-10 w-10 text-gray-400 mb-2" />
                  <span className="font-bold text-brand-primary">Upload Manual Book / SOP</span>
                  <p className="text-xs text-gray-400 mt-1">.pdf (Max 5MB)</p>

                  {/* Show new file name */}
                  {formData.file_sop && (
                    <p className="text-sm text-green-600 mt-2 font-medium bg-green-50 py-1 px-2 rounded-lg inline-block">
                      {formData.file_sop.name}
                    </p>
                  )}

                  {/* Show existing file if no new file selected */}
                  {!formData.file_sop && existingFiles.file_sop && (
                    <div className="mt-2 text-sm">
                      <p className="text-blue-600 font-medium mb-1">File saat ini tersimpan</p>
                      <a
                        href={existingFiles.file_sop}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-gray-500 hover:text-brand-primary underline"
                        onClick={(e) => e.stopPropagation()}
                      >
                        Lihat SOP
                      </a>
                    </div>
                  )}
                </label>
              </div>
            </div>
          </div>

          <div className="flex justify-end gap-3 pt-6 border-t">
            <Button variant="ghost" onClick={() => navigate('/inventaris/data')} type="button">
              Batal
            </Button>
            <Button variant="primary" type="submit" loading={loading} className="px-8 shadow-xl shadow-brand-primary/20">
              <Save size={18} className="mr-2" />
              {isEdit ? 'Simpan Perubahan' : 'Simpan Data'}
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
